services:
  - type: web
    name: jeevan-setu
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
